[32mINFO    [0m juju.model:model.py:2098 Deploying local:jammy/pgbouncer-1
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/1 [idle] active: 
  postgresql/2 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/tls-certificates-operator-22
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  tls-certificates-operator/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  tls-certificates-operator/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  tls-certificates-operator/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  tls-certificates-operator/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  tls-certificates-operator/0 [idle] active: 
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/1 [idle] active: 
  postgresql/2 [idle] active: Primary
  tls-certificates-operator/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql/0 [executing] waiting: Awaiting restart operation
  postgresql/1 [executing] waiting: Awaiting restart operation
  postgresql/2 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql/0 [executing] active: 
  postgresql/1 [executing] waiting: Awaiting restart operation
  postgresql/2 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql/0 [executing] active: 
  postgresql/1 [executing] active: 
  postgresql/2 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql/0 [executing] active: 
  postgresql/1 [executing] active: 
  postgresql/2 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/1 [executing] active: 
  postgresql/2 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/1 [executing] active: 
  postgresql/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/1 [idle] active: 
  postgresql/2 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/1 [idle] active: 
  postgresql/2 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/focal/mailman3-core-18
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [executing] maintenance: Installing mailman3,postfix,postfix-policyd-spf-python,spamassassin,spamc
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [executing] maintenance: Installing mailman3,postfix,postfix-policyd-spf-python,spamassassin,spamc
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [executing] maintenance: Installing python3-mailman-hyperkitty
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [idle] active: Ready (source version/commit e1d5a03)
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [idle] active: Ready (source version/commit e1d5a03)
  postgresql/0 [idle] active: 
  postgresql/1 [idle] active: 
  postgresql/2 [idle] active: Primary
  pgbouncer/1 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [idle] active: Ready (source version/commit e1d5a03)
  postgresql/0 [idle] active: 
  postgresql/1 [idle] active: 
  postgresql/2 [idle] active: Primary
  pgbouncer/1 [executing] blocked: waiting for backend database relation to initialise
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mailman3-core/0 [idle] active: Ready (source version/commit e1d5a03)
  pgbouncer/1 [executing] active: 
[32mINFO    [0m root:helpers.py:96 (0, '{"pgbouncer/1":{"workload-version":"1.21.0","machine":"5","opened-ports":null,"public-address":"10.219.178.54","charm":"local:jammy/pgbouncer-1","leader":true,"life":"alive","relation-info":[{"relation-id":10,"endpoint":"backend-database","related-endpoint":"database","application-data":{"data":"{\\"database\\": \\"pgbouncer\\", \\"extra-user-roles\\": \\"SUPERUSER\\", \\"requested-secrets\\": \\"[\\\\\\"username\\\\\\", \\\\\\"password\\\\\\", \\\\\\"tls\\\\\\", \\\\\\"tls-ca\\\\\\", \\\\\\"uris\\\\\\"]\\"}","database":"pgbouncer","endpoints":"10.219.178.215:5432","read-only-endpoints":"10.219.178.143:5432,10.219.178.30:5432","secret-tls":"secret://40ef7790-a6c3-4f19-8ce7-a364454204e4/ctaft8vfj651icp0jclg","secret-user":"secret://40ef7790-a6c3-4f19-8ce7-a364454204e4/ctaft8nfj651icp0jcl0","version":"14.13"},"local-unit":{"in-scope":false,"data":null},"related-units":{"postgresql/0":{"in-scope":true,"data":{"egress-subnets":"10.219.178.30/32","ingress-address":"10.219.178.30","private-address":"10.219.178.30"}},"postgresql/1":{"in-scope":true,"data":{"egress-subnets":"10.219.178.143/32","ingress-address":"10.219.178.143","private-address":"10.219.178.143"}},"postgresql/2":{"in-scope":true,"data":{"egress-subnets":"10.219.178.215/32","ingress-address":"10.219.178.215","private-address":"10.219.178.215"}}}},{"relation-id":13,"endpoint":"db","related-endpoint":"db","application-data":{},"local-unit":{"in-scope":false,"data":null},"related-units":{"mailman3-core/0":{"in-scope":true,"data":{"database":"mailman3","egress-subnets":"10.219.178.54/32","ingress-address":"10.219.178.54","private-address":"10.219.178.54"}}}},{"relation-id":9,"endpoint":"pgb-peers","related-endpoint":"pgb-peers","application-data":{"current_port":"6432","leader_ip":"10.219.178.54","pgb_dbs_config":"{\\"13\\": {\\"name\\": \\"mailman3\\", \\"legacy\\": true}}","pgbouncer_user_13_test":"{\\"user\\": \\"pgbouncer_user_13_test\\", \\"password\\": \\"skHTmbSdELZq7tGav9yjlr16\\", \\"database\\": \\"mailman3\\"}","readonly_dbs":"[\\"postgresql_test_app_database\\"]"},"local-unit":{"in-scope":true,"data":{"auth_file_set":"true","egress-subnets":"10.219.178.54/32","ingress-address":"10.219.178.54","pgb_dbs":"6f95661222dd47ebbaa1e3d98a7a61f3","private-address":"10.219.178.54"}}},{"relation-id":8,"endpoint":"upgrade","related-endpoint":"upgrade","application-data":{"dependencies":"{\\"charm\\": {\\"dependencies\\": {}, \\"name\\": \\"pgbouncer\\", \\"upgrade_supported\\": \\"\\u003e0\\", \\"version\\": \\"1\\"}, \\"snap\\": {\\"dependencies\\": {}, \\"name\\": \\"charmed-postgresql\\", \\"upgrade_supported\\": \\"^1\\", \\"version\\": \\"1.18.0\\"}}"},"local-unit":{"in-scope":true,"data":{"egress-subnets":"10.219.178.54/32","ingress-address":"10.219.178.54","private-address":"10.219.178.54","state":"idle"}}}]}}\n', '')
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.6    unsupported  02:05:13Z

App                        Version  Status  Scale  Charm                      Channel        Rev  Exposed  Message
mailman3-core                       active      1  mailman3-core              latest/stable   18  no       Ready (source version/commit e1d5a03)
pgbouncer                  1.21.0   active      1  pgbouncer                                   1  no       
postgresql                 14.13    active      3  postgresql                 14/edge        530  no       
tls-certificates-operator           active      1  tls-certificates-operator  latest/stable   22  no       

Unit                          Workload  Agent  Machine  Public address  Ports     Message
mailman3-core/0*              active    idle   5        10.219.178.54   25/tcp    Ready (source version/commit e1d5a03)
  pgbouncer/1*                active    idle            10.219.178.54             
postgresql/0                  active    idle   0        10.219.178.30   5432/tcp  
postgresql/1                  active    idle   1        10.219.178.143  5432/tcp  
postgresql/2*                 active    idle   2        10.219.178.215  5432/tcp  Primary
tls-certificates-operator/0*  active    idle   4        10.219.178.121            

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.219.178.30   juju-4204e4-0  ubuntu@22.04      Running
1        started  10.219.178.143  juju-4204e4-1  ubuntu@22.04      Running
2        started  10.219.178.215  juju-4204e4-2  ubuntu@22.04      Running
4        started  10.219.178.121  juju-4204e4-4  ubuntu@22.04      Running
5        started  10.219.178.54   juju-4204e4-5  ubuntu@20.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

machine-2: 01:40:38 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:40:38 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:40:38 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:40:41 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:40:41 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:40:41 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:40:47 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:40:47 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:40:47 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-2: 01:41:52 ERROR unit.postgresql/2.juju-log Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9ede181810>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.219.178.215', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ede181810>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/src/cluster.py", line 531, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.219.178.215', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ede181810>: Failed to establish a new connection: [Errno 111] Connection refused'))
machine-3: 01:50:10 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:50:10 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-0: 01:50:10 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-0: 01:50:13 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
machine-4: 01:54:11 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:54:11 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-tls-certificates-operator-0: 01:54:11 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-2: 01:54:40 ERROR unit.postgresql/2.juju-log certificates:12: Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.219.178.215', port=8008): Max retries exceeded with url: /cluster (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/src/cluster.py", line 531, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-2/charm/venv/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.219.178.215', port=8008): Max retries exceeded with url: /cluster (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))
machine-5: 02:00:27 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 02:00:27 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mailman3-core-0: 02:00:27 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-1: 02:03:52 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...