[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer/0 [idle] active: VIP: 10.119.212.228
  pgbouncer/2 [executing] active: 
  pgbouncer/3 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer/0 [executing] blocked: ha integration used without vip configuration
  pgbouncer/2 [idle] blocked: ha integration used without vip configuration
  pgbouncer/3 [executing] blocked: ha integration used without vip configuration
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer/0 [executing] blocked: ha integration used without vip configuration
  pgbouncer/2 [idle] blocked: ha integration used without vip configuration
  pgbouncer/3 [idle] blocked: ha integration used without vip configuration
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer/0 [executing] blocked: ha integration used without vip configuration
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer/0 [executing] blocked: ha integration used without vip configuration
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer/0 [executing] blocked: ha integration used without vip configuration
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer/0 [idle] blocked: ha integration used without vip configuration
  pgbouncer/2 [idle] blocked: ha integration used without vip configuration
  pgbouncer/3 [executing] blocked: ha integration used without vip configuration
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer/0 [idle] active: 
  pgbouncer/2 [idle] active: 
  pgbouncer/3 [idle] active: 
[32mINFO    [0m integration.relations.pgbouncer_provider.test_data_integrator_ha:test_data_integrator_ha.py:154 Data integrator host is 10.119.212.32
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.9    unsupported  01:56:09Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
data-integrator                    active      3  data-integrator           latest/edge    222  no       
hacluster                 2.1.2    active      3  hacluster                 2.4/stable     131  no       Unit is ready and clustered
pgbouncer                 1.21.0   active      3  pgbouncer                                  0  no       
postgresql                14.18    active      2  postgresql                14/edge        879  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  264  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
data-integrator/0*           active    idle   0        10.119.212.227            
  hacluster/0*               active    idle            10.119.212.227            Unit is ready and clustered
  pgbouncer/3                active    idle            10.119.212.227  6432/tcp  
data-integrator/1            active    idle   1        10.119.212.32             
  hacluster/1                active    idle            10.119.212.32             Unit is ready and clustered
  pgbouncer/0*               active    idle            10.119.212.32   6432/tcp  
data-integrator/2            active    idle   2        10.119.212.10             
  hacluster/2                active    idle            10.119.212.10             Unit is ready and clustered
  pgbouncer/2                active    idle            10.119.212.10   6432/tcp  
postgresql/0                 active    idle   4        10.119.212.83   5432/tcp  
postgresql/1*                active    idle   5        10.119.212.226  5432/tcp  Primary
self-signed-certificates/0*  active    idle   3        10.119.212.74             

Machine  State    Address         Inst id        Base          AZ               Message
0        started  10.119.212.227  juju-25072e-0  ubuntu@22.04  pkrvmqc4gcfdwos  Running
1        started  10.119.212.32   juju-25072e-1  ubuntu@22.04  pkrvmqc4gcfdwos  Running
2        started  10.119.212.10   juju-25072e-2  ubuntu@22.04  pkrvmqc4gcfdwos  Running
3        started  10.119.212.74   juju-25072e-3  ubuntu@22.04  pkrvmqc4gcfdwos  Running
4        started  10.119.212.83   juju-25072e-4  ubuntu@22.04  pkrvmqc4gcfdwos  Running
5        started  10.119.212.226  juju-25072e-5  ubuntu@22.04  pkrvmqc4gcfdwos  Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

machine-0: 01:37:52 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:37:52 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-0: 01:37:52 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 01:40:58 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:40:58 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:40:59 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:41:32 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:41:32 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:41:32 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:41:49 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:41:50 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:41:50 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:42:12 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:42:12 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-1: 01:42:13 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 01:42:16 ERROR unit.postgresql/1.juju-log Unable to get the state of the cluster
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 494, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 325, in connect
    self.sock = self._new_conn()
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7faaff96e8f0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/adapters.py", line 644, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.119.212.226', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faaff96e8f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/src/cluster.py", line 571, in are_replicas_up
    response = requests.get(
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-1/charm/venv/lib/python3.10/site-packages/requests/adapters.py", line 677, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.119.212.226', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faaff96e8f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
machine-2: 01:42:33 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:42:33 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-2: 01:42:33 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 01:42:42 ERROR unit.postgresql/1.juju-log database-peers:5: Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

unit-postgresql-0: 01:44:47 ERROR unit.postgresql/0.juju-log database-peers:5: Failed to list PostgreSQL database users: connection to server at "10.119.212.83", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

unit-pgbouncer-0: 01:46:09 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-2: 01:46:09 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-pgbouncer-3: 01:46:10 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...