[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.10   unsupported  01:52:02Z

App                  Version  Status       Scale  Charm                Channel      Rev  Exposed  Message
pgbouncer            1.21.0   error            3  pgbouncer            1/stable     639  no       hook failed: "backend-database-relation-changed"
postgresql           14.19    maintenance      3  postgresql           14/edge      918  no       installing PostgreSQL
postgresql-test-app           blocked          3  postgresql-test-app  latest/edge  406  no       No database integration available

Unit                    Workload     Agent      Machine  Public address  Ports     Message
postgresql-test-app/0   blocked      idle       0        10.112.187.137            No database integration available
  pgbouncer/1           blocked      executing           10.112.187.137            waiting for backend database relation to initialise
postgresql-test-app/1*  blocked      idle       1        10.112.187.96             No database integration available
  pgbouncer/0*          error        idle                10.112.187.96             hook failed: "backend-database-relation-changed"
postgresql-test-app/2   blocked      idle       2        10.112.187.48             No database integration available
  pgbouncer/2           blocked      executing           10.112.187.48             waiting for backend database relation to initialise
postgresql/0            waiting      executing  3        10.112.187.56   5432/tcp  awaiting for cluster to start
postgresql/1            maintenance  executing  4        10.112.187.67             (install) installing PostgreSQL
postgresql/2*           active       executing  5        10.112.187.66   5432/tcp  Primary (degraded)

Machine  State    Address         Inst id        Base          AZ             Message
0        started  10.112.187.137  juju-6b385e-0  ubuntu@22.04  runnervm3ublj  Running
1        started  10.112.187.96   juju-6b385e-1  ubuntu@22.04  runnervm3ublj  Running
2        started  10.112.187.48   juju-6b385e-2  ubuntu@22.04  runnervm3ublj  Running
3        started  10.112.187.56   juju-6b385e-3  ubuntu@22.04  runnervm3ublj  Running
4        started  10.112.187.67   juju-6b385e-4  ubuntu@22.04  runnervm3ublj  Running
5        started  10.112.187.66   juju-6b385e-5  ubuntu@22.04  runnervm3ublj  Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

machine-1: 01:46:34 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:46:34 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:49:21 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:49:21 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:49:45 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:49:45 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:50:07 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:50:07 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:50:34 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:50:34 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:51:04 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:51:04 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:51:11 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

unit-postgresql-2: 01:51:18 ERROR unit.postgresql/2.juju-log database:6: Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

unit-pgbouncer-0: 01:52:00 ERROR unit.pgbouncer/0.juju-log backend-database:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/src/charm.py", line 987, in <module>
    main(PgBouncerCharm)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 343, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 134, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 857, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 3142, in _on_relation_changed_event
    getattr(self.on, "database_created").emit(
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 857, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/src/relations/backend_database.py", line 211, in _on_database_created
    self.initialise_auth_function(self.collect_databases())
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1064, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/src/relations/backend_database.py", line 326, in initialise_auth_function
    with self.postgres._connect_to_database(dbname) as conn, conn.cursor() as cursor:
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 153, in _connect_to_database
    connection = psycopg2.connect(
  File "/var/lib/juju/agents/unit-pgbouncer-0/charm/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.112.187.66", port 5432 failed: FATAL:  no pg_hba.conf entry for host "10.112.187.96", user "relation-6", database "postgres", no encryption

unit-pgbouncer-0: 01:52:01 ERROR juju.worker.uniter.operation hook "backend-database-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...